### ISSUE TITLE
add numpy as project requirement

### ISSUE THREAD

**Issue by grant-humphries** [grant-humphries/rlis2osm#12]
apparently it is one, from my ubuntu virtual box:

```
Traceback (most recent call last):
  File "./bin/rlis2osm", line 22, in <module>
    sys.exit(rlis2osm.main.main())
  File "/home/ubuntu/rlis2osm/rlis2osm/main.py", line 228, in main
    dissolver.dissolve_ways(paths.combined, paths.dissolved)
  File "/home/ubuntu/rlis2osm/rlis2osm/dissolve.py", line 40, in dissolve_ways
    dissolve_geom = linemerge(geom_list)
  File "/home/ubuntu/rlis2osm/eggs/Shapely-1.5.17-py2.7-linux-x86_64.egg/shapely/ops.py", line 113, in linemerge
    result = lgeos.GEOSLineMerge(source._geom)
  File "/home/ubuntu/rlis2osm/eggs/Shapely-1.5.17-py2.7-linux-x86_64.egg/shapely/geometry/proxy.py", line 33, in _geom
    self.__geom__, n = self.factory(self.context)
  File "/home/ubuntu/rlis2osm/eggs/Shapely-1.5.17-py2.7-linux-x86_64.egg/shapely/geometry/multilinestring.py", line 134, in geos_multilinestring_from_py
    geom, ndims = linestring.geos_linestring_from_py(obs[l])
  File "/home/ubuntu/rlis2osm/eggs/Shapely-1.5.17-py2.7-linux-x86_64.egg/shapely/geometry/linestring.py", line 197, in geos_linestring_from_py
    ob = required(ob)
  File "/home/ubuntu/rlis2osm/eggs/Shapely-1.5.17-py2.7-linux-x86_64.egg/shapely/coords.py", line 31, in required
    return numpy.require(ob, numpy.float64, ["C", "OWNDATA"])
NameError: global name 'numpy' is not defined

```

**Comment by grant-humphries** [comment]
this may actually be a bug in shapely as numpy is supposed to be optional, opened a ticket [here](https://github.com/Toblerity/Shapely/issues/431) and am waiting to hear what the shapely devs think

**Comment by grant-humphries** [comment]
I may want to add numpy into the extras_require in setup.py as it may speed things up, planning to inquire about this

**Comment by grant-humphries** [comment]
numpy does provide a performance boost and it is required (unintentionally) in shapely 1.5.17.  I've added it as a requirement now and will move it to the `extras_require` section of setup.py on the release of shapely 1.6 as it sounds like it will be truly option then.  Follow these issues for updates:
* Toblerity/shapely#431
* Toblerity/shapely#433
